"""
Strategy Proposal Schema.

Defines the structure for new strategy ideas generated by the
research agent. Each proposal goes through sandbox testing before
any human approval.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from enum import Enum


class ProposalStatus(str, Enum):
    DRAFT = "draft"
    SANDBOX_PENDING = "sandbox_pending"
    SANDBOX_PASSED = "sandbox_passed"
    SANDBOX_FAILED = "sandbox_failed"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    ACTIVE = "active"


@dataclass
class StrategyProposal:
    """A proposed new strategy or strategy modification from the LLM."""
    proposal_id: str
    name: str
    description: str
    rationale: str  # Why this strategy might work

    # Strategy spec
    entry_conditions: List[str]
    exit_conditions: List[str]
    best_regimes: List[str]
    avoid_regimes: List[str]
    expected_rr: float = 1.5
    expected_win_rate: float = 0.50

    # Risk bounds
    max_position_size_pct: float = 0.01  # % of equity
    max_leverage: float = 5.0
    max_hold_time_hours: float = 24.0

    # Metadata
    status: ProposalStatus = ProposalStatus.DRAFT
    source_pattern: Optional[str] = None  # Which corpus pattern inspired it
    created_ts: float = 0.0
    sandbox_results: Optional[Dict[str, Any]] = None
    approval_notes: str = ""

    # Symbols this applies to (empty = all)
    target_symbols: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "name": self.name,
            "description": self.description,
            "rationale": self.rationale,
            "entry_conditions": self.entry_conditions,
            "exit_conditions": self.exit_conditions,
            "best_regimes": self.best_regimes,
            "avoid_regimes": self.avoid_regimes,
            "expected_rr": self.expected_rr,
            "expected_win_rate": self.expected_win_rate,
            "max_position_size_pct": self.max_position_size_pct,
            "max_leverage": self.max_leverage,
            "max_hold_time_hours": self.max_hold_time_hours,
            "status": self.status.value,
            "source_pattern": self.source_pattern,
            "created_ts": self.created_ts,
            "sandbox_results": self.sandbox_results,
            "approval_notes": self.approval_notes,
            "target_symbols": self.target_symbols,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "StrategyProposal":
        status_raw = d.get("status", "draft")
        try:
            status = ProposalStatus(status_raw)
        except ValueError:
            status = ProposalStatus.DRAFT
        return cls(
            proposal_id=d.get("proposal_id", ""),
            name=d.get("name", ""),
            description=d.get("description", ""),
            rationale=d.get("rationale", ""),
            entry_conditions=d.get("entry_conditions", []),
            exit_conditions=d.get("exit_conditions", []),
            best_regimes=d.get("best_regimes", []),
            avoid_regimes=d.get("avoid_regimes", []),
            expected_rr=float(d.get("expected_rr", 1.5)),
            expected_win_rate=float(d.get("expected_win_rate", 0.5)),
            max_position_size_pct=float(d.get("max_position_size_pct", 0.01)),
            max_leverage=float(d.get("max_leverage", 5.0)),
            max_hold_time_hours=float(d.get("max_hold_time_hours", 24.0)),
            status=status,
            source_pattern=d.get("source_pattern"),
            created_ts=float(d.get("created_ts", 0)),
            sandbox_results=d.get("sandbox_results"),
            approval_notes=d.get("approval_notes", ""),
            target_symbols=d.get("target_symbols", []),
        )

    def is_safe(self) -> bool:
        """Basic safety validation for a proposal."""
        if self.max_leverage > 25.0:
            return False
        if self.max_position_size_pct > 0.05:  # 5% max
            return False
        if self.expected_rr < 0.5:
            return False
        if not self.entry_conditions:
            return False
        if not self.exit_conditions:
            return False
        return True
