"""
Trade candidate abstraction and dual-world logging.

Every potential trade is a "candidate" - the ensemble says "this might work".
The LLM then decides: proceed, flat, or flip.
We log both worlds so we can measure LLM value.
"""

import csv
import json
import logging
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional

logger = logging.getLogger("bot.candidate")

_CANDIDATE_LOG_DIR = os.path.join("data", "analysis")
_CANDIDATE_LOG_FILE = os.path.join(_CANDIDATE_LOG_DIR, "trade_candidates.csv")

# CSV columns: timestamp, symbol, side, entry_type, ensemble_signal, ensemble_confidence,
# llm_action, llm_size_mult, llm_entry_adj, regime, triggers, realized_pnl, realized_r,
# hold_time_s, leverage_used, outcome


@dataclass
class TradeCandidate:
    """
    A potential trade generated by the ensemble.
    This is what the LLM sees and decides on.
    """
    # Core identifiers (no defaults)
    symbol: str
    side: str  # "LONG" or "SHORT"
    entry: float
    sl: float
    tp1: float
    tp2: float
    atr: float
    ensemble_confidence: float  # 0-100
    ensemble_strategy: str  # which strategy generated this
    entry_type: str  # "SCALP", "MEDIUM", "TREND", "REGIME"
    primary_driver: str  # which factor drove the signal
    regime: str  # regime at time of signal
    timestamp: float  # when candidate was generated

    # Optional/default fields
    trace_id: str = ""
    num_agree: int = 1
    strategies_agree: List[str] = field(default_factory=list)
    triggers: List[str] = field(default_factory=list)  # why LLM was called
    risk_reward_tp1: float = 1.0

    # LLM decision (filled in after LLM evaluates)
    llm_action: Optional[str] = None  # "proceed", "flat", "flip"
    llm_size_mult: float = 1.0
    llm_entry_adj: Optional[str] = None
    llm_confidence: Optional[float] = None
    llm_regime: Optional[str] = None
    llm_notes: Optional[str] = None
    llm_memory_update: Optional[str] = None

    # Realized outcome (filled in after trade closes)
    realized_pnl: Optional[float] = None
    realized_r: Optional[float] = None
    hold_time_s: Optional[float] = None
    leverage_used: Optional[float] = None
    close_reason: Optional[str] = None  # SL, TP1, TP2, TRAILING, EARLY_EXIT, TELEGRAM_CLOSE
    outcome: Optional[str] = None  # WIN, LOSS, BREAK_EVEN

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for CSV/JSON logging."""
        return asdict(self)

    @property
    def effective_size_mult(self) -> float:
        """Size multiplier after LLM decision."""
        if self.llm_action == "flat":
            return 0.0
        return self.llm_size_mult if self.llm_size_mult is not None else 1.0


class CandidateLogger:
    """
    Logs all trade candidates to CSV for dual-world analysis.
    Columns: ensemble decision, LLM decision, realized outcome, plus context.
    """

    def __init__(self):
        self._ensure_log()

    def _ensure_log(self):
        os.makedirs(_CANDIDATE_LOG_DIR, exist_ok=True)
        if not os.path.exists(_CANDIDATE_LOG_FILE):
            with open(_CANDIDATE_LOG_FILE, "w", newline="") as f:
                headers = [
                    "timestamp",
                    "symbol",
                    "side",
                    "entry_type",
                    "primary_driver",
                    "regime",
                    "triggers",
                    "ensemble_confidence",
                    "num_agree",
                    "strategies_agree",
                    "llm_action",
                    "llm_size_mult",
                    "llm_entry_adj",
                    "llm_confidence",
                    "llm_regime",
                    "realized_pnl",
                    "realized_r",
                    "hold_time_s",
                    "leverage_used",
                    "close_reason",
                    "outcome",
                ]
                csv.writer(f).writerow(headers)

    def log_candidate(self, candidate: TradeCandidate):
        """Log a candidate (with or without LLM decision + outcome)."""
        self._ensure_log()
        try:
            with open(_CANDIDATE_LOG_FILE, "a", newline="") as f:
                csv.writer(f).writerow([
                    f"{candidate.timestamp:.0f}",
                    candidate.symbol,
                    candidate.side,
                    candidate.entry_type,
                    candidate.primary_driver,
                    candidate.regime,
                    ";".join(candidate.triggers) if candidate.triggers else "",
                    f"{candidate.ensemble_confidence:.1f}",
                    candidate.num_agree,
                    ";".join(candidate.strategies_agree) if candidate.strategies_agree else "",
                    candidate.llm_action or "",
                    f"{candidate.llm_size_mult:.2f}" if candidate.llm_size_mult else "",
                    candidate.llm_entry_adj or "",
                    f"{candidate.llm_confidence:.2f}" if candidate.llm_confidence else "",
                    candidate.llm_regime or "",
                    f"{candidate.realized_pnl:.2f}" if candidate.realized_pnl is not None else "",
                    f"{candidate.realized_r:.2f}" if candidate.realized_r is not None else "",
                    f"{candidate.hold_time_s:.0f}" if candidate.hold_time_s is not None else "",
                    f"{candidate.leverage_used:.1f}" if candidate.leverage_used else "",
                    candidate.close_reason or "",
                    candidate.outcome or "",
                ])
        except Exception as e:
            logger.warning(f"Failed to log candidate: {e}")

    @staticmethod
    def load_candidates(path: str = _CANDIDATE_LOG_FILE) -> List[Dict[str, Any]]:
        """Load all candidates from CSV for analysis."""
        if not os.path.exists(path):
            return []
        candidates = []
        with open(path, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                candidates.append(row)
        return candidates
